// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClthamNIk5C-nU5-KPxHLzQp2DxBngCJE',
    appId: '1:788180306685:web:138875adc08f3ccf528c94',
    messagingSenderId: '788180306685',
    projectId: 'ecom-app2505',
    authDomain: 'ecom-app2505.firebaseapp.com',
    storageBucket: 'ecom-app2505.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaBY0n_0DK3b3tyMOeWRroJvg260-iJts',
    appId: '1:788180306685:android:13145943f6d840bf528c94',
    messagingSenderId: '788180306685',
    projectId: 'ecom-app2505',
    storageBucket: 'ecom-app2505.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMXgmyZZQHvP-gxCAJo9A9IBSe4C5TaN4',
    appId: '1:788180306685:ios:306c3a6e9df8d748528c94',
    messagingSenderId: '788180306685',
    projectId: 'ecom-app2505',
    storageBucket: 'ecom-app2505.appspot.com',
    iosClientId: '788180306685-jvarln66diaivpa2vst61kudt28bloo5.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );
}
